baseURL = "https://iot-arch.github.io/sbook/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "GB28181 Security Technology"
theme = "techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


copyright = "&copy;{year}, All Rights Reserved"

timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100



# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false
    [markup.highlight]
        codeFences = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true


