# Global menu section
# See https://gohugo.io/content-management/menus/
[[main]]
    name = "Home"
    url = "/"
    weight = 1
[[main]]
    name = "Books"
    url = "/post"
    weight = 2
[[main]]
    name = "Archives"
    url = "/archives"
    weight = 3
[[main]]
    name = "Articles"
    url = "#"
    weight = 4
